# Generated by Django 4.0.5 on 2022-07-07 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(default='nom', max_length=20)),
                ('prenom_demandeur', models.CharField(default='prénom', max_length=20)),
                ('mail', models.CharField(default='exemple@mail.com', max_length=40)),
                ('nom_de_la_machine', models.CharField(max_length=20)),
                ('url', models.CharField(default='sandbox.ensea.fr', max_length=20)),
                ('version_OS', models.CharField(choices=[('container debian 10.7', 'Container debian 10.7'), ('container debian 11.0', 'Container debian 11.0'), ('VM', 'VM')], default=1, max_length=21)),
                ('vpn', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('ports_TCP_Ext', models.CharField(max_length=5)),
                ('ports_UDP_Ext', models.CharField(max_length=5)),
                ('nombre_de_coeurs', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('ram', models.IntegerField()),
                ('alloc_HDD', models.CharField(max_length=10)),
                ('alloc_SSD', models.CharField(max_length=10)),
                ('autre', models.CharField(max_length=100)),
                ('utilisation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_début', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('date_destruction', models.DateField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('En fonctionnement', 'En fonctionnement'), ('En arrêt', 'En arrêt'), ('Détruite', 'Détruite'), ('A créer', 'A créer')], default=0, max_length=40)),
                ('date_de_demande', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
