# Generated by Django 4.0.5 on 2022-07-01 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_machine', models.CharField(max_length=20)),
                ('os_version', models.TextField()),
                ('ports_TCP_VPN', models.CharField(max_length=5)),
                ('ports_TCP_Ext', models.CharField(max_length=5)),
                ('ports_UDP_VPN', models.CharField(max_length=5)),
                ('ports_UDP_Ext', models.CharField(max_length=5)),
                ('cores', models.CharField(max_length=2)),
                ('ram', models.TextField()),
                ('alloc_HDD', models.TextField()),
                ('alloc_SSD', models.TextField()),
                ('autre', models.TextField()),
                ('nom_demandeur', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
