# Generated by Django 4.0.5 on 2022-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='autre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='etat',
            field=models.CharField(choices=[('En fonctionnement', 'En fonctionnement'), ('En arrêt', 'En arrêt'), ('Détruite', 'Détruite'), ('A créer', 'A créer')], default='A créer', max_length=40),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='mail',
            field=models.CharField(default='exemple@mail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='nom_demandeur',
            field=models.CharField(default='nom', max_length=30),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='prenom_demandeur',
            field=models.CharField(default='prénom', max_length=30),
        ),
    ]
