# Generated by Django 4.0.5 on 2022-07-05 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='formulaire',
            name='ports_TCP_VPN',
        ),
        migrations.RemoveField(
            model_name='formulaire',
            name='ports_UDP_VPN',
        ),
        migrations.AddField(
            model_name='formulaire',
            name='date_destruction',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='date_début',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='demande_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='etat',
            field=models.CharField(choices=[('En fonctionnement', 'En fonctionnement'), ('En arrêt', 'En arrêt'), ('Détruite', 'Détruite'), ('A créer', 'A créer')], default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='mail',
            field=models.CharField(default='exemple@mail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='prenom_demandeur',
            field=models.CharField(default='prénom', max_length=20),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='url',
            field=models.CharField(default='sandbox.ensea.fr', max_length=20),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='use',
            field=models.TextField(default='usage'),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='alloc_HDD',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='alloc_SSD',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='cores',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='nom_demandeur',
            field=models.CharField(default='nom', max_length=20),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='os_version',
            field=models.CharField(choices=[('container debian 10.7', 'container debian 10.7'), ('container debian 11.0', 'container debian 11.0'), ('VM', 'VM')], default=1, max_length=21),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
