# Generated by Django 4.0.5 on 2022-07-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_alter_formulaire_autre_alter_formulaire_etat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='date_de_demande',
        ),
    ]
